[profile.default]
optimizer = true
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
zetaTestnet = "${ZETA_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
